### ISSUE TITLE
Has this project been abandoned? 

### ISSUE THREAD

**Issue by coderberry** [HHS/pillbox_docs#6]
I submitted for my key weeks ago and still haven't received one. I was wondering if this is still being maintained.

Thanks and sorry to discuss this here. I wasn't sure where else to ask.

**Comment by ghost** [comment]
Eric, thanks for letting me know. I'll check into this. I've seen other API keys going though so not sure what's happening.

Regardless, will get you a key ASAP.

On Oct 22, 2015, at 5:27 PM, Eric Berry <notifications@github.com<mailto:notifications@github.com>> wrote:

I submitted for my key weeks ago and still haven't received one. I was wondering if this is still being maintained.

Thanks and sorry to discuss this here. I wasn't sure where else to ask.

**Comment by ghost** [comment]
Everything looks good on our side. I see the requests you made and emails sent to you with API keys.  I sent the info to the email address you provided.  Please let me know if you do/don't receive my email. Thanks
