### ISSUE TITLE
Confusion with RxImage - maybe add some documentation to README?

### ISSUE THREAD

**Issue by cknoxrun** [HHS/pillbox_docs#7]
Hi there, Pillbox looks really interesting, but I'm trying to understand the difference (in terms of data)  between Pillbox and another NLM project, RxImage (http://rximage.nlm.nih.gov/docs/doku.php)? Should I grab data from both locations if I want to have complete coverage? Thanks!

**Comment by ghost** [comment]
Apologies for the confusion.  Pillbox should be everything you need. It's contains data on all pills marketed in the US (extracted from FDA SPL/DailyMed) and combines images from several sources/projects (NLM Pillbox, NLM RxImage, Department of Veterans Affairs, pharmaceutical companies).

Does this help?

**Comment by cknoxrun** [comment]
That helps a lot, thanks for the info and awesome project!

**Comment by Mauvila** [comment]
I agree with the original poster in that the distinction between PillBox and C3PI (which I assume is the same thing as RxImage) is unclear in the official documentation (especially considering both are projects of the NLM).  As you mentioned, it seems that RxImage images are very standardized images of medications, and that PillBox is a more general image database that includes images from RxImage and other sources.  But overall I think it would help to include this explanation officially.  

I also think other things need to be documented, e.g. RxCUI appears to only link with the SCDs for medications that are not marketed under a brand name (brand name drugs appear to be linked only to the SBD).  Ideally, the brand name drugs will be linked with SCDs or both SCD and SBD, as SCD does not pertain only to non-brand name drugs but rather all drugs (whereas SBD is specific for the specified brand name).  In other words, if I'm creating a patient-directed med-rec app which shows patients pictures of pills they are allegedly prescribed and asks them which ones they are taking, for every medication I will have to not only use the SCD that is listed in their chart, but to go into UMLS and dig up all the related SBDs and then search with those as well. I think a lot of people will assume that the SCD covers all the medications for that strength, and it should be mentioned in documentation that it currently excludes brand names.
